#!/usr/bin/env python3
"""
Incident Log Generator
Generates realistic Nginx combined-format access logs with $request_time appended.
Simulates production traffic with subtle hidden anomalies for incident investigation.
Standard library only.
"""

import sys
import random
import time
from datetime import datetime, timezone, timedelta

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate synthetic Nginx access logs for triage.")
    parser.add_argument("-n", "--lines", type=int, default=500000, help="Total log lines to generate (default: 500000)")
    parser.add_argument("-o", "--output", type=str, default="access.log", help="Output file path (default: access.log)")
    args = parser.parse_args()

    total_lines = args.lines
    output_file = args.output

    print(f"[*] Generating {total_lines:,} log lines into '{output_file}'...")
    start_wall = time.time()

    # Time span: 2 hours of traffic starting at 14:00 UTC
    start_time = datetime(2026, 10, 1, 14, 0, 0, tzinfo=timezone.utc)
    total_duration_sec = 7200  # 2 hours

    # Endpoints pool
    endpoints = [
        ("GET", "/api/v1/products", 0.025, 0.010),
        ("GET", "/api/v1/search", 0.045, 0.015),
        ("GET", "/api/v1/cart", 0.030, 0.010),
        ("POST", "/api/v1/cart/items", 0.065, 0.020),
        ("POST", "/api/v1/checkout", 0.120, 0.035),
        ("POST", "/api/v1/auth/login", 0.050, 0.015),
        ("GET", "/static/css/main.css", 0.005, 0.002),
        ("GET", "/static/js/app.js", 0.008, 0.003),
        ("GET", "/healthz", 0.002, 0.001),
    ]

    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
        "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
        "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0"
    ]

    # Pre-generate clean IP pool
    regular_ips = [
        f"{random.randint(11, 190)}.{random.randint(1, 254)}.{random.randint(1, 254)}.{random.randint(1, 254)}"
        for _ in range(800)
    ]

    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

    # Problem 1: 502 burst window (seconds into the run)
    burst_start_sec = 2800  # ~46 min in
    burst_end_sec = 3500    # ~58 min in (~11 min window)
    burst_endpoint = "/api/v1/checkout"

    # Problem 2: Slow creep endpoint
    creep_endpoint = "/api/v1/search"

    # Problem 3: Abusive IP
    abusive_ip = "198.51.100.42"
    abuse_start_sec = 1800
    abuse_end_sec = 5400

    # Chunked writes for fast file I/O
    chunk = []
    chunk_size = 20000

    with open(output_file, "w", encoding="utf-8", buffering=1024 * 1024) as f:
        for i in range(total_lines):
            # Calculate timestamp progression with slight jitter
            fraction = i / total_lines
            current_sec = fraction * total_duration_sec + random.uniform(-1.0, 1.0)
            current_sec = max(0, min(total_duration_sec, current_sec))
            current_dt = start_time + timedelta(seconds=current_sec)

            # Problem 4: ~0.1% malformed lines
            if random.random() < 0.001:
                malformed_type = i % 4
                if malformed_type == 0:
                    chunk.append("CORRUPTED_ENTRY_NULL_BYTE\\x00\\x00\\x1f\\x8b\n")
                elif malformed_type == 1:
                    chunk.append(f"{regular_ips[i % len(regular_ips)]} - - [{current_dt.strftime('%d/%b/%Y:%H:%M:%S +0000')}] INCOMPLETE_REQUEST_NO_STATUS\n")
                elif malformed_type == 2:
                    chunk.append(f"GET /index.php 200 452 0.012\n")
                else:
                    chunk.append(f"{regular_ips[i % len(regular_ips)]} - - [INVALID_DATE_FORMAT] \"GET /api/v1/products HTTP/1.1\" 200 1200 \"-\" \"curl/7.68.0\" 0.021\n")
                
                if len(chunk) >= chunk_size:
                    f.writelines(chunk)
                    chunk.clear()
                continue

            # Check if this line is generated by the abusive IP
            is_abuse_req = (abuse_start_sec <= current_sec <= abuse_end_sec) and (random.random() < 0.12)
            if is_abuse_req:
                ip = abusive_ip
                method, path, base_lat, lat_jitter = ("POST", "/api/v1/auth/login", 0.045, 0.010)
                status = 401 if random.random() < 0.88 else 200
                bytes_sent = 312
                latency = max(0.005, random.gauss(base_lat, lat_jitter))
            else:
                ip = regular_ips[i % len(regular_ips)]
                method, path, base_lat, lat_jitter = random.choice(endpoints)
                bytes_sent = random.randint(250, 4800)
                latency = max(0.001, random.gauss(base_lat, lat_jitter))
                status = 200

                # Check Problem 1: 502 burst
                if burst_start_sec <= current_sec <= burst_end_sec and path == burst_endpoint:
                    if random.random() < 0.74:
                        status = 502
                        bytes_sent = 166
                        latency = random.uniform(2.1, 5.4)  # Upstream gateway timeout

                # Check Problem 2: Slow creep
                if path == creep_endpoint:
                    # Latency creeps upwards proportionally over time from 45ms up to 3.8s
                    creep_factor = (current_sec / total_duration_sec) ** 2.2
                    latency += creep_factor * 3.8

                # Routine noise errors (0.3% across endpoints)
                if status == 200 and random.random() < 0.003:
                    status = 404 if random.random() < 0.6 else 500

            # Nginx format:
            # $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time
            time_str = f"{current_dt.day:02d}/{months[current_dt.month - 1]}/{current_dt.year}:{current_dt.hour:02d}:{current_dt.minute:02d}:{current_dt.second:02d} +0000"
            ua = user_agents[i % len(user_agents)]
            line = f'{ip} - - [{time_str}] "{method} {path} HTTP/1.1" {status} {bytes_sent} "-" "{ua}" {latency:.3f}\n'
            chunk.append(line)

            if len(chunk) >= chunk_size:
                f.writelines(chunk)
                chunk.clear()

        if chunk:
            f.writelines(chunk)
            chunk.clear()

    elapsed = time.time() - start_wall
    rate = total_lines / elapsed if elapsed > 0 else 0
    print(f"[✓] Successfully wrote {total_lines:,} lines to '{output_file}' in {elapsed:.2f}s ({rate:,.0f} lines/sec).")

if __name__ == "__main__":
    main()
